<?php

namespace TS\TalkBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UtentiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtentiRepository extends EntityRepository
{
}
